"""added Park model and relationships

Revision ID: 277d71702176
Revises: 1fc5b8bdfce6
Create Date: 2024-08-05 18:18:25.466724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277d71702176'
down_revision = '1fc5b8bdfce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('park_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_rides_park_id_parks'), 'parks', ['park_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rides_park_id_parks'), type_='foreignkey')
        batch_op.drop_column('park_id')

    op.drop_table('parks')
    # ### end Alembic commands ###
